#ifndef SHOT_TUNING_H
#define SHOT_TUNING_H
#include "Robotmap.h"

#if COMPETITION_BOT
//#define NEAR_SHOT_POWER 0.94
//#define NEAR_SHOT_ANGLE 84.0
//
//#define AUTO_1_SHOT_POWER NEAR_SHOT_POWER
//#define AUTO_1_SHOT_ANGLE NEAR_SHOT_ANGLE
//
//#define TRUSS_SHOT_POWER 0.95
//#define TRUSS_SHOT_ANGLE 89.0
//
//#define SHOOTER_POWER_TURNS_1 (0.5)
//
//#define STEEP_SHOT_POWER (0.9)
//#define STEEP_SHOT_ANGLE (90.5)

// 
#define NEAR_SHOT_POWER 0.9
#define NEAR_SHOT_ANGLE 85.0

#define AUTO_1_SHOT_POWER NEAR_SHOT_POWER
#define AUTO_1_SHOT_ANGLE NEAR_SHOT_ANGLE-1.0

#define FEEDER_TRUSS_SHOT_POWER 1.10
#define FEEDER_TRUSS_SHOT_ANGLE 98
#define FEEDER_TRUSS_SHOT_DELAY 0
#define FEEDER_TRUSS_SHOT_TOLERANCE 2

#define NEAR_TRUSS_SHOT_POWER 0.90
#define NEAR_TRUSS_SHOT_ANGLE 100.0
#define NEAR_TRUSS_SHOT_DELAY 0
#define NEAR_TRUSS_SHOT_TOLERANCE 3

#define STEEP_SHOT_POWER (.6)
#define STEEP_SHOT_ANGLE (95)

#define IRS_SHOT_POWER (.5)
#define IRS_SHOT_ANGLE (101)
#define IRS_SHOT_TOLERANCE (1.25)

#else
#define NEAR_SHOT_POWER 0.94
#define NEAR_SHOT_ANGLE 85.0

#define AUTO_1_SHOT_POWER NEAR_SHOT_POWER
#define AUTO_1_SHOT_ANGLE NEAR_SHOT_ANGLE

#define FEEDER_TRUSS_SHOT_POWER 1.10
#define FEEDER_TRUSS_SHOT_ANGLE 98
#define FEEDER_TRUSS_SHOT_DELAY 0
#define FEEDER_TRUSS_SHOT_TOLERANCE 2

#define NEAR_TRUSS_SHOT_POWER 0.90
#define NEAR_TRUSS_SHOT_ANGLE 100.0
#define NEAR_TRUSS_SHOT_DELAY 0
#define NEAR_TRUSS_SHOT_TOLERANCE 3

#define STEEP_SHOT_POWER (.6)
#define STEEP_SHOT_ANGLE (95)

#define IRS_SHOT_POWER (.5)
#define IRS_SHOT_ANGLE (101)
#define IRS_SHOT_TOLERANCE (1.25)
#endif
#endif
